---
title: "POLG HEK cell lines - single cell mitochondrial mutational burden"
author: "Yu-Hsin Josch Hsieh"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("~/Ludwig_lab/scmtMMB/POLG_HEK/code/")
```

### Load packages

```{r packages, message=FALSE, warning=FALSE}
source("../../global_func/variant_calling.R")
source("../../global_func/quantifyMMB.R")
library(Matrix)
library(dplyr)
library(tidyr)
library(SummarizedExperiment)
library(ggplot2)
library(scales)
library(data.table)
'%ni%' <- Negate('%in%')
```

## Load the metadata and the mito data

```{r data loading, message=FALSE, warning=FALSE}
# Load the seurat object
mtVar.bulk.df <- read.csv("../output/2_mtVar.bulk.meta.csv", row.names = "X")
CTRL_dnV <- mtVar.bulk.df %>% filter(occurrence == "Private" & condition == "CTRL") %>% pull(variant)
KI36_dnV <- mtVar.bulk.df %>% filter(occurrence != "Parental" & condition == "KI36") %>% pull(variant)
KIA2_dnV <- mtVar.bulk.df %>% filter(occurrence != "Parental" & condition == "KIA2") %>% pull(variant)

mmat.list <- list(readRDS("../POLG_HEK_large_data_files/output/2_mmtx.CTRL.rds")[CTRL_dnV,],
                     readRDS("../POLG_HEK_large_data_files/output/2_mmtx.KI36.rds")[KI36_dnV,],
                     readRDS("../POLG_HEK_large_data_files/output/2_mmtx.KIA2.rds")[KIA2_dnV,])
cov.list <- list(readRDS("../POLG_HEK_large_data_files/output/2_mtDNA_pos_coverage.CTRL.rds"),
                 readRDS("../POLG_HEK_large_data_files/output/2_mtDNA_pos_coverage.KI36.rds"),
                 readRDS("../POLG_HEK_large_data_files/output/2_mtDNA_pos_coverage.KIA2.rds"))

HEK_metadata <- read.csv("../output/1_HEK_metadata.csv",header = TRUE, row.names = 1)
color_vec <- c("CTRL" = "#2780FF", "KI36" = "#960096", "KIA2" = "#000090")
```

```{r Calculate MMB}

scmtMMB_HEK <- do.call(rbind,lapply(1:3,function(idx){
                 rbind(
                   quantify_MMB(mmat.list[[idx]], cov.list[[idx]],names(color_vec)[idx]),
                   quantify_MMB_psedobulk(mmat.list[[idx]], cov.list[[idx]],names(color_vec)[idx]))
                    }))

md <- HEK_metadata %>% dplyr::select(atacUMAP_1, atacUMAP_2,seurat_clusters, mtDNA_depth) %>% tibble::rownames_to_column("barcode")
scmtMMB_HEK <- scmtMMB_HEK %>% left_join(., md, by = "barcode")

write.csv(scmtMMB_HEK, "../output/5_scmtMMB_HEK.csv", quote = FALSE, row.names = TRUE)
```

### Single cell MMB at Complex level
- MSS 
```{r , message=FALSE, warning=FALSE, fig.width=7, fig.height=1.2}

scmtMMB_HEK_com <- scmtMMB_HEK %>% filter(symbol %in% c("CI", "CIII", "CIV", "CV", "tRNA", "rRNA", "Total")) %>% 
                      mutate(symbol = factor(symbol,levels = c("CI", "CIII", "CIV", "CV", "tRNA", "rRNA", "Total")))

(p1 <- scmtMMB_HEK_com %>% 
          ggplot(aes(x = sample, y = MSS + 1)) +
          geom_jitter(aes(fill = sample), size = 0.1, color = "grey") + 
          geom_violin(aes(fill = sample), scale = "width", alpha = 0.8) +
          scale_fill_manual(values = color_vec) +
          geom_point(data = scmtMMB_HEK_com %>% filter(barcode == "pseudobulk"), 
                     aes(group = sample), shape = 23, size = 2, fill = "white") + # overlay bulk data as point
          facet_wrap(~symbol, ncol =10) + 
          theme_bw() + xlab(NULL) +
          scale_y_log10(breaks = trans_breaks("log10", function(x) 10^x), 
                             labels = trans_format("log10", math_format(10^.x))) + 
          theme(aspect.ratio=1/1, axis.title.x=element_blank(), axis.text.x=element_blank(), axis.ticks.x=element_blank()) +
          labs(y = bquote(paste(log[10], "(MSS + 1)"))))

ggsave(plot = p1, "../plot/51_MSS_complex.pdf")
```

- MSS weighted by heteroplasmy
```{r , message=FALSE, warning=FALSE, fig.width=7, fig.height=1.2}
(p2 <- scmtMMB_HEK_com %>% 
          ggplot(aes(x = sample, y =  MSS_weighted + 0.01)) +
          geom_jitter(aes(fill = sample), size = 0.1, color = "grey") + 
          geom_violin(aes(fill = sample), scale = "width", alpha = 0.8) +
          scale_fill_manual(values = color_vec) +
          geom_point(data = scmtMMB_HEK_com %>% filter(barcode == "pseudobulk"), 
                     aes(group = sample), shape = 23, size = 2, fill = "white") + # overlay bulk data as point
          facet_wrap(~symbol, ncol =10) + 
          theme_bw() + xlab(NULL) +
          scale_y_continuous(trans = log2_trans(), 
                             breaks = trans_breaks("log2", function(x) 2^x), 
                             labels = trans_format("log2", math_format(2^.x))) + 
          theme(aspect.ratio=1/1, axis.title.x=element_blank(), 
                axis.text.x=element_blank(), axis.ticks.x=element_blank()) +
          labs(y = bquote(paste(log[2], "(Weighted MSS + 0.01)"))))

ggsave(plot = p2, "../plot/52_MSS_weighted_complex.pdf")
```
- Mutations per MB
```{r , message=FALSE, warning=FALSE, fig.width=7, fig.height=1.2}
(p3 <- scmtMMB_HEK_com %>%
          ggplot(aes(x = sample, y = mutation_per_MB + 1)) +
          geom_jitter(aes(fill = sample), size = 0.1, color = "grey") + 
          geom_violin(aes(fill = sample), scale = "width", alpha = 0.8) +
          scale_fill_manual(values = color_vec) +
          geom_point(data = . %>% filter(barcode == "pseudobulk"), 
                     aes(group = sample), shape = 23, size = 2, fill = "white") + # overlay bulk data as point
          facet_wrap(~symbol, ncol =10) + 
          theme_bw() + xlab(NULL) +
          scale_y_log10(breaks = trans_breaks("log10", function(x) 10^x), 
                             labels = trans_format("log10", math_format(10^.x))) + 
          theme(aspect.ratio=1/1, axis.title.x=element_blank(), axis.text.x=element_blank(), axis.ticks.x=element_blank()) +
          labs(y = bquote(paste(log[10], "(Mutation per MB + 1)"))))

# ggsave(plot = p3, "../plot/3_mutation_per_MB_complex.pdf") # , scale = 1.5

```
```{r , message=FALSE, warning=FALSE, fig.width=6, fig.height=2}
(p4 <- scmtMMB_HEK %>% filter(symbol == "Total") %>% 
   ggplot(aes(x = log10(mtDNA_depth), y = mutation_per_MB + 1)) +
  geom_point(aes(col = sample)) + facet_wrap(~sample) + 
  scale_color_manual(values = color_vec) + 
  theme_bw() + ylab("Mutation per MB (Total)") + theme(legend.position="none") +
  geom_smooth(method = "lm"))
ggsave(plot = p4, paste0("../plot/54_CorDepth_MpMB.pdf"))


(p5 <- scmtMMB_HEK %>% filter(symbol == "Total") %>% ggplot(aes(x = log10(mtDNA_depth), y = MSS_weighted, col = sample)) +
  geom_point() + facet_wrap(~sample) + scale_color_manual(values = color_vec) + 
  theme_bw() + ylab("Weighted MSS (Total)") + theme(legend.position="none") +
  geom_smooth(method = "lm"))
ggsave(plot = p5, paste0("../plot/55_CorDepth_MSSw.pdf"))

(p6 <- scmtMMB_HEK %>% filter(symbol == "Total") %>% 
    ggplot(aes(x= mutation_per_MB +1, y = MSS_weighted, color = sample)) +
  geom_point(size = 0.01) + scale_color_manual(values = color_vec) +
  facet_wrap(~sample, scales = "free", ncol = 3) + 
  theme_bw() + theme(legend.position="none") +
  geom_smooth(method = "lm")) 
ggsave(plot = p6, paste0("../plot/56_Cor_MpMB_MSSw.pdf"))

library(ggpubr)
scmtMMB_HEK_tl <- scmtMMB_HEK %>% filter(symbol == "Total" & barcode != "pseudobulk") %>%
  mutate(mtDNA_depth = log10(mtDNA_depth), mutation_per_MB = mutation_per_MB + 1)
p4s <-ggscatter(
  scmtMMB_HEK_tl, x = "mtDNA_depth", y = "mutation_per_MB",
  color = "sample", palette = color_vec,
  add = "reg.line"
  ) + facet_wrap(~sample) +
  stat_cor(
    aes(label = paste(..rr.label.., ..p.label.., sep = "~`,`~")), 
    label.y = 2750)
ggsave(plot = p4s, paste0("../plot/54s_CorDepth_MpMB.pdf"), width=6, height=4)


p5s <-ggscatter(
  scmtMMB_HEK_tl, x = "mtDNA_depth", y = "MSS_weighted",
  color = "sample", palette = color_vec,
  add = "reg.line"
  ) + facet_wrap(~sample) +
  stat_cor(
    aes(label = paste(..rr.label.., ..p.label.., sep = "~`,`~")), 
    label.y = 25)
ggsave(plot = p5s, paste0("../plot/55s_CorDepth_MSSw.pdf"), width=6, height=4)


p6s <- ggscatter(
  scmtMMB_HEK_tl, x = "mutation_per_MB", y = "MSS_weighted",
  color = "sample", palette = color_vec,
  add = "reg.line"
  ) + facet_wrap(~sample) +
  stat_cor(
    aes(label = paste(..rr.label.., ..p.label.., sep = "~`,`~")), 
    label.y = 25)
ggsave(plot = p6s, paste0("../plot/56s_Cor_MpMB_MSSw.pdf"), width=6, height=4)


p7 <- scmtMMB_HEK %>% filter(symbol == "Total") %>% filter(complete.cases(.)) %>% 
   ggplot(aes(x = log10(mtDNA_depth), y = mutation_per_MB + 1)) +
  geom_point(aes(col = sample)) + facet_wrap(~seurat_clusters) + 
  scale_color_manual(values = color_vec) + 
  theme_bw() + ylab("Mutation per MB (Total)") + theme(legend.position="none") +
  geom_smooth(method = "lm")
ggsave(plot = p7, paste0("../plot/57_CorDepth_MpMB_cluster.pdf"), width=6, height=6)

p7s <- ggscatter(
  scmtMMB_HEK_tl, x = "mtDNA_depth", y = "mutation_per_MB",
  color = "seurat_clusters", 
  add = "reg.line"
  ) + facet_wrap(~seurat_clusters) +
  stat_cor(
    aes(label = paste(..rr.label.., ..p.label.., sep = "~`,`~")), 
    label.y = 2750)
ggsave(plot = p7s, paste0("../plot/57s_CorDepth_MpMB_cluster.pdf"), width=6, height=6)

```



```{r scmtMMB UMAP, fig.width=4.5 fig.height=4}

lapply(c("CI", "CIII", "CIV", "CV", "tRNA", "rRNA", "Total"), function(cat){
  
  df <- scmtMMB_HEK %>% dplyr::filter(symbol == cat & barcode != "pseudobulk") %>% 
                       mutate(log10_MpMB = log10(mutation_per_MB), log2_MSSw = log2(MSS_weighted)) %>% 
                       mutate(log10_MpMB = ifelse(is.infinite(log10_MpMB), NA, log10_MpMB),
                              log2_MSSw = ifelse(is.infinite(log2_MSSw), NA, log2_MSSw))
  
  p <- ggplot(df, aes(x = atacUMAP_1, y = atacUMAP_2, color = log10_MpMB)) +
  geom_point(size = 0.01) + 
  scale_color_gradientn(colors = BuenColors::jdb_palette("solar_extra"), 
                        limit = quantile(df$log10_MpMB, c(0.02,0.98), na.rm =TRUE)) +
  theme(aspect.ratio=1) + theme_classic() + ggtitle(paste0("MpMB_", cat)) 
  p.nl <- p + theme_void() + Seurat::NoLegend() 
  p.leg <- ggpubr::get_legend(p) %>% ggpubr::as_ggplot()
  ggsave(plot = p.nl, paste0("../plot/5_MpMB_UMAP/MpMB_", cat,".pdf"), width = 2, height = 2)
  ggsave(plot = p.leg, paste0("../plot/5_MpMB_UMAP/MpMB_", cat,".leg.pdf"), width = 3, height = 2)
  
  p <- ggplot(df, aes(x = atacUMAP_1, y = atacUMAP_2, color = log2_MSSw)) +
  geom_point(size = 0.01) + scale_colour_viridis_c() +
  theme(aspect.ratio=1) + theme_classic() + ggtitle(paste0("MSS_weighted_", cat))
  p.nl <- p + theme_void() + Seurat::NoLegend() 
  p.leg <- ggpubr::get_legend(p) %>% ggpubr::as_ggplot()
  ggsave(plot = p.nl, paste0("../plot/5_MSSw_UMAP/MSSw_", cat,".pdf"), width = 2, height = 2)
  ggsave(plot = p.leg, paste0("../plot/5_MSSw_UMAP/MSSw_", cat,".leg.pdf"), width = 3, height = 2)

})

```
```